#!/usr/bin/env bash

# Copyright 2014 Alexander Fahlke
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

bin=`which $0`
bin=`dirname ${bin}`
bin=`cd "$bin"; pwd`

export OOZIE_TOOL_CONF_DIR="$bin"/../conf
export OOZIE_TOOL_LIBEXEC_DIR="$bin"/../libexec

# check if the config file exists
echo -e "Checking for config file"
echo "--------------------------------------------------------------------------------"
if [ ! -f "${OOZIE_TOOL_CONF_DIR}/config.ini" ]; then
	echo "ERROR config.ini not found!"
	echo "aborting tests"
	exit 1
else
	echo "OK config.ini found"
fi
echo ""
source "${OOZIE_TOOL_CONF_DIR}/config.ini.tpl"

# debug output
echo -e "Config debug output"
echo "--------------------------------------------------------------------------------"
echo "hostname:  ${OOZIE_HOSTNAME}"
echo "port:      ${OOZIE_PORT}"
echo "oozie bin: ${OOZIE_BIN}"
echo ""

# check if we can connect to the port on the given host
echo -e "Connecting to \"${OOZIE_HOSTNAME}:${OOZIE_PORT}\""
echo "--------------------------------------------------------------------------------"
echo ""

# check if oozie returns anything
echo -e "Checking oozie on \"${OOZIE_HOSTNAME}:${OOZIE_PORT}\""
echo "--------------------------------------------------------------------------------"
echo ""
